---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/5013/workspace/2023MavenWebAppPipelineAnsible/target/2023MavenWebAppPipelineAnsible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebAppPipelineAnsible.war"
        remote_src: no

    - name: Restart tomcat
        shell: |
        /opt/tomcat/bin/shutdown.sh
        /opt/tomcat/bin/startup.sh
